trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      # Start screen recording
      ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i :0.0 -y test_execution.mp4 &
      RECORD_PID=$!

      # Run the Selenium test
      python test-auto.py

      # Stop screen recording
      kill $RECORD_PID
      
    displayName: 'Run Selenium Test'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'login_page.png'
      ArtifactName: 'screenshots'
      publishLocation: 'Container'
    condition: succeededOrFailed()
