parameters:
- name: screenshots
  displayName: Screenshots
  type: object
  default:
    - '1_login_page.png'
    - '2_enter_email_page.png'
    - '3_next_button_clicked.png'
    - '4_next_button_clicked_page_shown.png'
    - '5_enter_pwd_page.png'
    - '6_signed_in_page.png'
    - '7_pop_up_off.png'
    - '8_tours.png'
    - '9_menu_opened.png'
    - '10_tableau_de_bord.png'

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      python test-auto.py
    displayName: 'Run Selenium Test'

  - ${{ each screenshot in parameters.screenshots }}:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/${{ screenshot }}'
        ArtifactName: 'screenshots'
        publishLocation: 'Container'
      condition: succeededOrFailed()
