parameters:
- name: screenshots
  displayName: Screenshots
  type: object
  default:
    - 'login_page.png'
    - 'enter_email_page.png'
    - 'next_button_clicked.png'
    - 'next_button_clicked_page_shown.png'
    - 'enter_pwd_page.png'
    - 'signed_in_page.png'
    - 'pop_up_off.png'
    - 'menu_opened.png'

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      python test-auto.py
    displayName: 'Run Selenium Test'

  - ${{ each screenshot in parameters.screenshots }}:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/${{ screenshot }}'
        ArtifactName: 'screenshots'
        publishLocation: 'Container'
      condition: succeededOrFailed()
