trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    
      # Run the Selenium test
      python test-auto.py
      
    displayName: 'Run Selenium Test'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: |
        login_page.png
        enter_email_page.png
        next_button_clicked.png
      ArtifactName: 'screenshots'
      publishLocation: 'Container'
    condition: succeededOrFailed()
