trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      python test_script.py
    displayName: 'Run Selenium Test'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'login_page.png'
      ArtifactName: 'screenshots'
      publishLocation: 'Container'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'enter_email_page.png'
      ArtifactName: 'screenshots'
      publishLocation: 'Container'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'next_button_clicked.png'
      ArtifactName: 'screenshots'
      publishLocation: 'Container'
    condition: succeededOrFailed()
