trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      python test-auto.py
    displayName: 'Run Selenium Test'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'linkedin_homepage_full.png'
      ArtifactName: 'screenshots'
      publishLocation: 'Container'
    condition: succeededOrFailed()
